import { Model, DataTypes, Optional } from 'sequelize';
import { sequelize } from '../config/db';

export interface UserAttributes {
  id: string;
  workos_id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  profile_picture_url: string | null;
}

// id is generated by the DB so it's optional on creation
type UserCreationAttributes = Optional<UserAttributes, 'id'>;

export class User extends Model<UserAttributes, UserCreationAttributes> {
  declare id: string;
  declare workos_id: string;
  declare email: string;
  declare first_name: string | null;
  declare last_name: string | null;
  declare profile_picture_url: string | null;
  declare readonly createdAt: Date;
  declare readonly updatedAt: Date;
}

User.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    workos_id: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true,
    },
    email: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true,
    },
    first_name: {
      type: DataTypes.STRING(255),
      allowNull: true,
    },
    last_name: {
      type: DataTypes.STRING(255),
      allowNull: true,
    },
    profile_picture_url: {
      type: DataTypes.STRING(1024),
      allowNull: true,
    },
  },
  {
    sequelize,
    tableName: 'users',
    timestamps: true,
    underscored: true,
  }
);

// ─── Helper functions (same interface as before) ──────────────────────────────

export interface UpsertUserParams {
  workos_id: string;
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  profile_picture_url?: string | null;
}

export async function upsertUser(params: UpsertUserParams): Promise<User> {
  const [user] = await User.upsert({
    ...params,
    first_name: params.first_name ?? null,
    last_name: params.last_name ?? null,
    profile_picture_url: params.profile_picture_url ?? null,
  });
  return user;
}

export async function findUserByWorkosId(workosId: string): Promise<User | null> {
  return User.findOne({ where: { workos_id: workosId } });
}

export async function findUserById(id: string): Promise<User | null> {
  return User.findByPk(id);
}
